const Events = Object.freeze({
    browser: Object.freeze({
        click: 'click',
        contextMenu: 'contextmenu',
        keyUp: 'keyup',
        keyDown: 'keydown',
        resize: 'resize',
        wheel: 'wheel',
        change: 'change',
        mouseDown: 'mousedown',
        mouseMove: 'mousemove',
        mouseOut: 'mouseout',
        contentLoaded: 'DOMContentLoaded',
        fullScreenChange: 'fullscreenchange',
        load: 'load',
        input: 'input',
        error: 'error',
    }),
    openLayers: Object.freeze({
        add: 'add',
        remove: 'remove',
        boxCancel: 'boxcancel',
        boxDrag: 'boxdrag',
        boxEnd: 'boxend',
        boxStart: 'boxstart',
        drawStart: 'drawstart',
        drawEnd: 'drawend',
        drawAbort: 'drawabort',
        modifyStart: 'modifystart',
        modifyEnd: 'modifyend',
        moveEnd: 'moveend',
        translateStart: 'translatestart',
        translateEnd: 'translateend',
        error: 'error',
        change: 'change',
        snap: 'snap',
        propertyChange: 'propertychange',
        preRender: 'prerender',
        postRender: 'postrender',
        renderComplete: 'rendercomplete',
        singleClick: 'singleclick',
        pointerMove: 'pointermove'
    }),
    custom: Object.freeze({
        toolbarDirectionChange: 'oltb.toolbar.direction.change',
        browserStateCleared: 'oltb.browser.state.cleared',
        mapLayerAdded: 'oltb.mapLayer.added',
        mapLayerRemoved: 'oltb.mapLayer.removed',
        featureLayerAdded: 'oltb.featureLayer.added',
        featureLayerRemoved: 'oltb.featureLayer.removed',
        featureEdited: 'oltb.feature.edited',
        featureRemoved: 'oltb.feature.removed',
        colorChange: 'oltb.color.change',
        activeFeatureLayerChange: 'oltb.active.feature.layer.change',
        ready: 'oltb.is.ready'
    })
});

export { Events };