const ShortcutKeys = Object.freeze({
    overviewTool: 'A',
    bookmarkTool: 'B',
    coordinatesTool: 'C',
    directionTool: 'D',
    exportPngTool: 'E',
    fullscreenTool: 'F',
    myLocationTool: 'G',
    homeTool: 'H',
    infoTool: 'I',
    graticuleTool: 'J',
    scaleLineTool: 'K',
    layerTool: 'L',
    measureTool: 'M',
    resetNorthTool: 'N',
    importVectorLayerTool: 'O',
    drawTool: 'P',
    zoomInTool: 'Q',
    refreshPageTool: 'R',
    splitViewTool: 'S',
    themeTool: 'T',
    settingsTool: 'U',
    editTool: 'V',
    zoomOutTool: 'W',
    notificationsTool: 'X',
    debugInfoTool: 'Y',
    magnifyTool: 'Z',
    helpTool: 'F1'
});

export { ShortcutKeys };