const SHORTCUT_KEYS = {
    overview: 'A',
    bookmark: 'B',
    coordinate: 'C',
    toolbarDirection: 'D',
    exportPNG: 'E',
    fullScreen: 'F',
    myLocation: 'G',
    home: 'H',
    info: 'I',
    graticule: 'J',
    scaleLine: 'K',
    layer: 'L',
    measure: 'M',
    resetNorth: 'N',
    importVectorLayer: 'O',
    draw: 'P',
    zoomIn: 'Q',
    refreshPage: 'R',
    splitView: 'S',
    toolbarTheme: 'T',
    settings: 'U',
    edit: 'V',
    zoomOut: 'W',
    notifications: 'X',
    debugInfo: 'Y',
    magnify: 'Z',
    help: 'F1'
};

export { SHORTCUT_KEYS };