const ShortcutKeys = Object.freeze({
    overviewTool: 'A',
    bookmarkTool: 'B',
    coordinatesTool: 'C',
    directionTool: 'D',
    exportPngTool: 'E',
    fullscreenTool: 'F',
    myLocationTool: 'G',
    homeTool: 'H',
    infoTool: 'I',
    graticuleTool: 'J',
    scaleLineTool: 'K',
    layerTool: 'L',
    measureTool: 'M',
    resetNorthTool: 'N',
    importVectorLayerTool: 'O',
    drawTool: 'P',
    zoomInTool: 'Q',
    refreshPageTool: 'R',
    splitViewTool: 'S',
    themeTool: 'T',
    zoomBoxTool: 'U',
    editTool: 'V',
    zoomOutTool: 'W',
    translationTool: 'X',
    scissorsTool: 'Y',
    magnifyTool: 'Z',
    helpTool: '1',
    settingsTool: '2',
    debugInfoTool: '3',
    notificationTool: '4',
});

export { ShortcutKeys };